sudo: false
language: python
python: 3.5
env:
  - TOX_ENV=py27
  - TOX_ENV=py33
  - TOX_ENV=py34
  - TOX_ENV=py35
  - TOX_ENV=pypy

script:
  - ./bin/test_standalone.sh
  - python -m pip install setuptools pip sphinx tox -U
  - tox -e $TOX_ENV
  - ./bin/check_readme.sh

branches:
  except:
    - standalone
