language: python

python:
  - 2.6
  - 2.7
  - 3.2
  - pypy

before_install: pip install --use-mirrors tox

install: python setup.py install
script: ./.travis-runtox.py

branches:
  except:
    - standalone

