# stage: test supported Python versions
sudo: false
language: python

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - pypy
  - pypy3

branches:
  except:
    - standalone

stages:
  - docker
  - test

jobs:
  include:

    - stage: docker
      sudo: required
      services:
        - docker
      install: []
      scirpt:
        - bin/test-docker.sh

    - stage: test
      install:
        - pip install -U setuptools pip sphinx tox tox-travis
      script:
        - ./bin/test_standalone.sh
        - tox
        - ./bin/check_readme.sh
